frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**'

backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**'

ml:
  - changed-files:
    - any-glob-to-any-file: 'ml-engine/**'

documentation:
  - changed-files:
    - any-glob-to-any-file: 
      - 'docs/**'
      - '*.md'

ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

docker:
  - changed-files:
    - any-glob-to-any-file:
      - '**/Dockerfile*'
      - '**/docker-compose*.yml'
